// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUuRevnpBfgIPJEfohQFQ4akB7spxM6xk',
    appId: '1:63385484402:web:7d43f5fed7ccfe906896eb',
    messagingSenderId: '63385484402',
    projectId: 'fire-3phasiko',
    authDomain: 'fire-3phasiko.firebaseapp.com',
    storageBucket: 'fire-3phasiko.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZbM2C5VtL1I8B2mrDsH11g101HflLuHs',
    appId: '1:63385484402:android:0bd8aaca23ae78766896eb',
    messagingSenderId: '63385484402',
    projectId: 'fire-3phasiko',
    storageBucket: 'fire-3phasiko.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmItACTU7cF3GXk29cJ09IRA_SB44SLbw',
    appId: '1:63385484402:ios:f7aeb0857157899c6896eb',
    messagingSenderId: '63385484402',
    projectId: 'fire-3phasiko',
    storageBucket: 'fire-3phasiko.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmItACTU7cF3GXk29cJ09IRA_SB44SLbw',
    appId: '1:63385484402:ios:f7aeb0857157899c6896eb',
    messagingSenderId: '63385484402',
    projectId: 'fire-3phasiko',
    storageBucket: 'fire-3phasiko.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUuRevnpBfgIPJEfohQFQ4akB7spxM6xk',
    appId: '1:63385484402:web:d654f79f1925b0e66896eb',
    messagingSenderId: '63385484402',
    projectId: 'fire-3phasiko',
    authDomain: 'fire-3phasiko.firebaseapp.com',
    storageBucket: 'fire-3phasiko.firebasestorage.app',
  );

}